name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  aws-tf:
    runs-on: [ self-hosted, ubuntu, example]
    steps:
      - uses: actions/checkout@v2
      - run: echo "hello aws"
